# 식품의 정보
# 가격이 제일 비싼 식품의 정보를 조회.

SELECT PRODUCT_ID,PRODUCT_NAME,PRODUCT_CD,CATEGORY,PRICE
from FOOD_PRODUCT
order by PRICE DESC
limit 1;


SELECT PRODUCT_ID,PRODUCT_NAME,PRODUCT_CD,CATEGORY,PRICE
from FOOD_PRODUCT
where PRICE = (select MAX(PRICE) from FOOD_PRODUCT)

